=== mateofigueroamcf/Ejercicio_6/ListaCursos.dtd
<!ELEMENT listacursos (curso)+>
<!ELEMENT curso (alumno)+>
<!ELEMENT alumno (dni, nombre, apellido, segApellido?, listaasignaturas)>
<!ELEMENT listaasignaturas (asignatura+)>
<!ELEMENT asignatura (nombre, profesor)>
<!ATTLIST asignatura codigo CDATA #REQUIRED>
<!ELEMENT profesor (nrp, nombre, apellido, segApellido?)>
<!ELEMENT dni (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT segApellido (#PCDATA)>
<!ELEMENT nrp (#PCDATA)>

=== mateofigueroamcf/Ejercicio_6/ListaCursos.xml
<?xml version="1.0" encoding="UTF-8" ?>

<!DOCTYPE listacursos SYSTEM "ListaCursos.dtd">
<listacursos>
    <curso>
        <alumno>
            <dni>3429392</dni>
            <nombre>Mateo</nombre>
            <apellido>Casta√±o</apellido>
            <listaasignaturas>
                <asignatura codigo="ce921831">
                    <nombre>software web</nombre>
                    <profesor>
                        <nrp>23</nrp>
                        <nombre>camilo</nombre>
                        <apellido>gallego</apellido>
                    </profesor>
                </asignatura>
            </listaasignaturas>
        </alumno>
    </curso>
</listacursos>
